### ISSUE TITLE
Please don't delete class definitions: they're useful for Python typehints

### ISSUE THREAD

**Issue by TheDiveO** [seveas/python-prctl#18]
As it is, python-prctl deletes the class definitions such as for `Capset` after it has initialized. This has the drawback that it is no longer possible to use Python typehints on the Capset objects. Please don't delete these valuable definitions and allow typehinting in code using your `prctl`.

**Comment by seveas** [comment]
Hi @TheDiveO,

I've not used these typehints before. Could you give an example of how you would use them and what the benefit would be?

**Comment by TheDiveO** [comment]
Sure! Assume that we want to print the list of capabilities in a `Capset` object. The type hint goes after the argument name and helps Python editors and linters to understand that we don't want to get any kind of object, but only `Capset`s. The `-> None` declares that our function is to return nothing.

```
def print_caps(caps: Capset) -> None:
    pass
```

Type hinting is not trying to make Python a statically typed language; instead, it helps (to my experience) with catching a good deal of mistakes during the coding stage. Pycharm has some great support for it and often catches things I would have overlooked.

**Comment by seveas** [comment]
Sounds useful enough!

**Comment by seveas** [comment]
Fixed in b15227a
