### ISSUE TITLE
support for python3.8?

### ISSUE THREAD

**Issue by n8v8R** [seveas/python-prctl#22]
* pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
___
`pip install -U python-prctl` producing

> Collecting python-prctl
>   Using cached https://files.pythonhosted.org/packages/7a/90/61935e2530a76f41e9e4f8ba0fe073d4ad0a3e16c4953156253f939fb057/python-prctl-1.7.tar.gz
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

which as far as I can tell is being an issue with python 3.8

**Comment by seveas** [comment]
Seems to be working fine now.
