### ISSUE TITLE
Constants defined in two modules at random

### ISSUE THREAD

**Issue by hramrach** [seveas/python-prctl#26]
Some constants are defined in prctl and some in _prctl

prctl.PR_FP_EXC_SW_ENABLE

_prctl.PR_FP_EXC_DISABLED

Please decide which it is and move all constants to one of them.

**Comment by hramrach** [comment]
Hello,
can you, please, share more details how this was addressed?

**Comment by seveas** [comment]
It was not. This issue is bogus.

Op wo 28 okt. 2020 12:37 schreef Michal Suchánek <notifications@github.com>:

**Comment by hramrach** [comment]
in what way is it bogus?

**Comment by hramrach** [comment]
What can I say?
Your library is bogus
