### ISSUE TITLE
pip install prctl==1.6.1 failing

### ISSUE THREAD

**Issue by d3matt** [seveas/python-prctl#8]
Apparently, https://pypi.python.org/simple/prctl/ is missing the 1.6.1 tarball

**Comment by binary1230** [comment]
+1 on this

**Comment by binary1230** [comment]
workaround for anyone getting here, you can do:
```
pip install git+git://github.com/seveas/python-prctl.git@v1.6.1
```

@seveas do you know, is this a matter of just taking the release tarball from https://github.com/seveas/python-prctl/releases/tag/v1.6.1 and uploading it to pypi?  Would you like some help maintaining that? I'd be willing to take a shot at it

**Comment by binary1230** [comment]
hey, I think I was just being dense or something, it's working fine if I do:

```pip3 install python-prctl==1.6.1```

sample python code
```python3
import prctl
prctl.set_name("test")
```

**Comment by daniviga** [comment]
[prctl](https://pypi.python.org/simple/prctl/) != [python-prctl](https://pypi.python.org/simple/python-prctl/)

Latter can be installed via
```
$ pip install python-prctl
```

**Comment by seveas** [comment]
You'll need to install the correct package, as @daniviga points out.
